// SPDX-License-Identifier: LicenseRef-ChemoDose-Academic-NonCommercial
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {calculateRegimen, filterEntries, summaryText} from '../src/catalogue.mjs';
const cat = JSON.parse(readFileSync(new URL('../../../data/catalogue.json', import.meta.url), 'utf8'));
const ack = {confirmed: true, reviewer: '合成数据测试'};
const inputs = {heightCm: 180, weightKg: 80, renalFunction: {value: 50, unit: 'mL/min', method: '合成测试值，非患者', confirmed: true}, alternatives: {'r056-d01': 1}};
// Independent expected arithmetic at BSA=2 m², weight=80 kg, renal=50 mL/min.
// Values are recorded from the reviewed PDF dose rows, not generated by the engine.
const expected = [
  [150,450,[640,480],[840,420]], [250,450,[640,480],[840,420]],
  [[160,200],[640,480],[840,420]], [250,[640,480],[840,420]],
  [[160,200],[640,480],400,1000,[150,200],1000], [432,160,[640,480],[840,420]],
  [[180,200],1200,160,[640,480],[840,420]], [[180,200],1200,250,[640,480],[840,420]],
  [150,100,1000], [100,150], [100,250], [150,450], [250,450],
  [[180,200],1200,160], [[180,200],1200,[160,200]], [[180,200],1200,250],
  [[180,200],1200,160,375], [160,112.5,200,180,1200,200], [200,112.5,200,180,1000,200],
  [100,150], [150,100,1000], [[180,200],1200,160],
  [[180,200],1200,160,[640,480],[840,420]], [[180,200],1200,[160,200],[640,480],[840,420]],
  [150,450,[640,480],[840,420]], [[180,200],1200,[160,200],[640,480]],
  [[180,200],1200,160,[320,160]], [200,1200,350,[320,160]],
  [180,1200,160,150], [[180,200],1200,[160,200]], [[180,200],1200,160],
  [[180,200],1200,350], [160,150], [200,1200], [150,450,[640,480]],
  [150,1200,[640,480]], [160,[320,160]], [150,1200], [150,1200],
  [[180,200],1200,[160,200]], [[180,200],1200,160], [[180,200],1200,350],
  [200,1200], [150,1200], [150,1200], [150,100,1000],
  [[180,200],1200,250,375], [150,100,1000],
  [1000,200,1000,[160,200]], [1000,200,1000,[160,200]],
  [[180,200],1200,160], [[180,200],1200,160], [25], [1], [2.5], [20], [150], [400], [125],
];
for (let i = 0; i < expected.length; i++) {
  test(`PDF dose regression r${String(i+1).padStart(3,'0')}: ${cat.regimens[i].name}`, () => {
    const result = calculateRegimen(cat, cat.regimens[i].id, inputs, ack);
    assert.equal(result.status, 'ok', JSON.stringify(result));
    assert.deepEqual(result.rows.map(r => {
      const q = r.result.quantities.map(q => q.valueMg);
      return q.length === 1 ? q[0] : q;
    }), expected[i]);
  });
}
test('52 regimens, seven single-drug references, 18 cards; all rows trace to the supplied scan', () => {
  assert.equal(cat.regimens.length, 59); assert.equal(cat.referenceCards.length, 18);
  assert.equal(cat.regimens.filter(r => r.entryType === 'regimen').length, 52);
  assert.deepEqual(cat.regimens.filter(r => r.legacyIndex).map(r => r.legacyIndex), Array.from({length:46},(_,i)=>i+1));
  const all = [...cat.regimens, ...cat.referenceCards];
  assert.equal(new Set(all.map(r => r.id)).size, all.length);
  assert.equal(new Set(cat.regimens.map(r => [r.section,r.subtype,r.name].join('|'))).size, 59);
  for (const r of all) {
    assert.equal(r.clinicalReview, 'pending');
    for (const entry of [r, ...(r.drugs || [])]) {
      assert.ok(entry.sourcePdfPages.length > 0);
      assert.deepEqual(entry.sourceBookPages, entry.sourcePdfPages.map(p => p - 17));
      assert.ok(entry.sourcePdfPages.every(p => p >= 48 && p <= 97));
    }
  }
});
test('PD-1 regimens retain separate dosing phases and correct different cycle intervals', () => {
  const p = cat.regimens[17], c = cat.regimens[18];
  for (const r of [p,c]) {
    assert.deepEqual(r.drugs.map(d => d.phase), [1,1,1,2,2,2]);
    assert.equal(r.drugs[2].name, r.drugs[5].name);
  }
  assert.match(p.drugs[0].schedule, /每21天/);
  assert.match(p.drugs[5].schedule, /每21天/);
  assert.deepEqual(p.drugs[5].sourcePdfPages, [60]);
  assert.match(c.drugs[0].schedule, /每28天/);
  assert.match(c.drugs[2].schedule, /每14天/);
  assert.match(c.drugs[4].schedule, /每14天/);
});
test('TC cycles, H/P courses, weekly H loading, and radiation level corrections remain distinct', () => {
  assert.equal(cat.regimens[37].drugs[0].duration, '共4周期');
  assert.equal(cat.regimens[38].drugs[0].duration, '共6周期');
  assert.equal(cat.regimens[0].drugs[3].duration, '共6周期');
  for (const i of [22,23,24]) assert.equal(cat.regimens[i].drugs.at(-1).duration, '完成1年');
  assert.deepEqual(cat.regimens[26].drugs.at(-1).dose, [4,2]);
  assert.match(cat.referenceCards.find(c => c.name === '新辅助全身治疗后的放疗').body, /I级全乳放疗 \[1A\] 或全乳\+瘤床加量 \[2A\]/);
});
test('missing renal function blocks the whole regimen, with no partial rows', () => {
  const result = calculateRegimen(cat, 'r001', {heightCm:180,weightKg:80}, ack);
  assert.equal(result.status, 'blocked'); assert.equal(result.rows, undefined);
  assert.match(result.issues[0].message, /卡铂/);
});
test('tamoxifen requires an explicit alternative and preserves per-administration frequency', () => {
  assert.equal(calculateRegimen(cat,'r056',{},ack).status,'blocked');
  for (const i of [0,1]) {
    const r = calculateRegimen(cat,'r056',{alternatives:{'r056-d01':i}},ack);
    assert.equal(r.rows[0].result.quantities[0].valueMg, [10,20][i]);
    assert.match(r.rows[0].result.quantities[0].schedule, i===0 ? /每日2次/ : /每日1次/);
  }
});
test('explicit acknowledgement is required; shipped clinical review remains pending', () => {
  for (const a of [null,{}, {confirmed:true,reviewer:''}, {confirmed:false,reviewer:'x'}])
    assert.equal(calculateRegimen(cat,'r001',inputs,a).status,'blocked');
  assert.equal(calculateRegimen(cat,'c001',inputs,ack).status,'blocked');
  assert.equal(cat.regimens[0].clinicalReview,'pending');
});
test('search respects section/subtype and copied sheet retains stages and full provenance', () => {
  assert.ok(filterEntries(cat,{section:'术前新辅助治疗',subtype:'HER2阳性',query:'TCbHP'}).every(r=>r.section==='术前新辅助治疗'&&r.subtype==='HER2阳性'));
  assert.equal(filterEntries(cat,{section:'保乳术后治疗',query:'卡铂'}).length,0);
  const text = summaryText(cat,calculateRegimen(cat,'r018',inputs,ack));
  for (const phrase of ['第一阶段','第二阶段','PDF 56、59、60','PDF 60 页','112.50 mg','核对人','非处方','不相加']) assert.ok(text.includes(phrase),phrase);
  assert.equal(summaryText(cat,{status:'blocked'}),'');
});
